package com.men.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStudent<M extends BaseStudent<M>> extends Model<M> implements IBean {

	
	public void setId(int id) {
		set("id", id);
	}
	
	public int getId() {
		return getInt("id");
	}
	
	public void setName(String name) {
		set("name", name);
	}
	
	public String getName() {
		return getStr("name");
	}
	
	public void setClasses(String classes) {
		set("classes", classes);
	}
	
	public String getClasses() {
		return getStr("classes");
	}
	
	public void setAge(int age) {
		set("age", age);
	}
	
	public int getAge() {
		return getInt("age");
	}
	
	public void setSex(String sex) {
		set("sex", sex);
	}
	
	public String getSex() {
		return getStr("sex");
	}
	
	public void setTel(String tel) {
		set("tel", tel);
	}
	
	public String getTel() {
		return getStr("tel");
	}
	
}

